### ISSUE TITLE
OAK-D integration

### ISSUE THREAD

**Issue by sbis04** [sbis04/yoga-instructor#14]
## TODO:

- [x] Connection with Raspberry pi
- [x] Starting and stopping of recognition
- [x] UI for the OAK connection --> in onboarding
- [x] Record OAK UI update --> in recognition screen
- [x] Camera stream of OAK-D
- [x] Add settings for updating **raspi path** of the scripts
