### ISSUE TITLE
Add profile/settings screen

### ISSUE THREAD

**Issue by sbis04** [sbis04/yoga-instructor#15]
## TODO

- [ ] Add profile details editing
- [ ] Stars and accuracy
- [ ] Personal info
- [ ] Weekly stats (with total time)
- [ ] Expandable for the poses done (with stars)
- [ ] Set targets (time, number of asanas & accuracy)
- [ ] Settings (pose holding time, raspi path, feedback, contact us, terms & conditions, privacy policy).
- [ ] Log out button
