### ISSUE TITLE
Database uploading

### ISSUE THREAD

**Issue by sbis04** [sbis04/yoga-instructor#16]
## TODO

- [ ] Upload all the videos on Firebase storage
- [ ] Add to MUX
- [ ] Update the MUX link on Firebase
- [ ] Upload remaining pose images (except those in beginners track)
