### ISSUE TITLE
TFLite integration

### ISSUE THREAD

**Issue by sbis04** [sbis04/yoga-instructor#7]
## TODO

- [x] Set up TFLite
- [x] Load and use model result
- [x] Manage resource on the preview screen
- [x] Add TFLite to recognizer screen
- [x] Fix bugs on recognizer screen
- [x] Add all pose models
