### ISSUE TITLE
Show joint points

### ISSUE THREAD

**Issue by sbis04** [sbis04/yoga-instructor#8]
## TODO

- [x] Store detected point array
- [x] Generate skeleton using CustomPainter by joining points
- [x] Overlay on cam view

**Comment by sbis04** [comment]
**Archived this** but still in the testing app, have to integrate to the main **Sofia** app.

**Comment by sbis04** [comment]
The **OAK** part is done 🎉

**Comment by sbis04** [comment]
Closing this for the moment, will open later while working on the normal mobile camera version 😎
