### ISSUE TITLE
User performance overview

### ISSUE THREAD

**Issue by sbis04** [sbis04/yoga-instructor#9]
## Tasks

- [x] Show a user performance widget
- [x] Enter stars, accuracy, time
- [x] onClick - show each pose time
